### ISSUE TITLE
Any way to change the font?

### ISSUE THREAD

**Issue by jeznag** [image-charts/documentation#4]
Is it possible to change the font of the chart? It looks quite different from the google charts font. I can't see any options documented.

**Comment by FGRibreau** [comment]
Hello !

Sorry for the delay we had quite an hard-time in March, currently no, it's not possible. 
However you can always change the font size see in [chart title](https://documentation.image-charts.com/reference/chart-title/), [chart legend](https://documentation.image-charts.com/reference/legend-text-and-style/)...

Don't hesitate to take an enterprise subscription to help us priorize our roadmap :+1:
