### ISSUE TITLE
[Guide] How to generate a QR Code from Google App Script

### ISSUE THREAD

**Issue by FGRibreau** [image-charts/documentation#8]
```js
  var imageData = UrlFetchApp.fetch('https://image-charts.com', {
    'method' : 'post',
    'payload' : {
      'cht': 'qr',
      'chl': 'https://google.com',
      'chs': '300x300'
  }}).getContent();
```

**Comment by kkeel** [comment]
This works to get the Qr data but when I try to input that data to google docs it renders either as an array of numbers or a bunch of ? boxes and gibberish. What am I missing in how to format this in my app script?

**Comment by FGRibreau** [comment]
If you wish to add it to a google doc, use the URL form instead "https://image-charts.com/chart?cht=qr&chl=https://google.com&chs=300x300" @kkeel :)
